Repository tidelabs/tidechain, pull requests merged in 2022-04, with the labels that each got.

#81 Minor fixes on comments and codes of quorum pallet
  frame/quorum/src/lib.rs
Labels: A0-pleasereview, C1-low 📌, B0-silent, D3-trivial 🧸

#80 Add `MarketMakerLimitFeeAmount`
  Cargo.lock
  frame/fees/src/lib.rs
  frame/fees/src/mock.rs
  frame/fees/src/tests.rs
  frame/oracle/src/lib.rs
  frame/oracle/src/mock.rs
  frame/quorum/src/lib.rs
  frame/quorum/src/tests.rs
  frame/quorum/src/weights.rs
  frame/tidefi/src/mock.rs
  runtime/common/config/tidefi.rs
  runtime/lagoon/src/weights/pallet_fees.rs
  runtime/tidechain/src/weights/pallet_fees.rs
Labels: A0-pleasereview, C1-low 📌, B1-releasenotes, D1-audited 👍

#82 Update epoch for `TIFI` staking
  runtime/common/config/consensus.rs
  runtime/common/config/tidefi.rs
  runtime/common/constants.rs
Labels: A0-pleasereview, C1-low 📌, B1-releasenotes, D3-trivial 🧸, A1-needsburnin

#83 Fix rustdoc-publish
  .gitlab-ci.yml
Labels: A0-pleasereview, C1-low 📌, B0-silent, D1-audited 👍

#85 Verify proposal existence before commit vote for a given proposal_id
  frame/quorum/src/lib.rs
  frame/quorum/src/tests.rs
Labels: A0-pleasereview, C3-medium 📣, B1-releasenotes, D9-needsaudit 👮

#89 Replace proposal's block number validation
  frame/quorum/src/lib.rs
  frame/quorum/src/tests.rs
Labels: A0-pleasereview, C3-medium 📣, B1-releasenotes, D9-needsaudit 👮

#93 Add validator documentation
  docs/assets/explorer-create-account.gif
  docs/assets/explorer-new-bond.gif
  docs/assets/explorer-new-validator.gif
  docs/assets/explorer-session-key.gif
  docs/assets/explorer-validate.gif
  docs/assets/validator-add-account.png
  docs/run-validator.md
Labels: A0-pleasereview, C1-low 📌, B0-silent, D2-notlive 💤

#95 Add `try-runtime` feature
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  cli/src/cli.rs
  cli/src/command.rs
  node/service/Cargo.toml
  runtime/common/api.rs
  runtime/lagoon/Cargo.toml
  runtime/tidechain/Cargo.toml
Labels: A0-pleasereview, C1-low 📌, B0-silent, D1-audited 👍

#96 Do not reserve the slippage percentage
  frame/oracle/src/lib.rs
  frame/oracle/src/tests.rs
Labels: A0-pleasereview, C1-low 📌, B0-silent, D1-audited 👍

#97 Allow limit order to match smaller price
  Cargo.lock
  frame/oracle/src/lib.rs
  frame/oracle/src/tests.rs
Labels: A0-pleasereview, C1-low 📌, B1-releasenotes, D1-audited 👍

#98 Prepare `0.2.3` release
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  frame/asset-registry/Cargo.toml
  frame/fees/Cargo.toml
  frame/oracle/Cargo.toml
  frame/quorum/Cargo.toml
  frame/security/Cargo.toml
  frame/tidefi-rpc/Cargo.toml
  frame/tidefi-stake/Cargo.toml
  frame/tidefi/Cargo.toml
  node/client/Cargo.toml
  node/rpc/Cargo.toml
  node/service/Cargo.toml
  runtime/lagoon/Cargo.toml
  runtime/lagoon/src/lib.rs
  runtime/tidechain/Cargo.toml
  runtime/tidechain/src/lib.rs
Labels: A0-pleasereview, C1-low 📌, B0-silent, D1-audited 👍

#100 Refactored oracle pallet unit tests
  frame/oracle/src/tests.rs
Labels: A0-pleasereview, C1-low 📌, B0-silent, D3-trivial 🧸

#102 Update to latest substrate
  Cargo.lock
  cli/Cargo.toml
  cli/src/cli.rs
  cli/src/command.rs
  frame/assets/src/functions.rs
  frame/assets/src/lib.rs
  frame/assets/src/tests.rs
  node/client/Cargo.toml
  node/service/Cargo.toml
  node/service/res/lagoon.json
  node/service/res/tidechain.json
  node/service/src/chain_spec.rs
  node/service/src/lib.rs
  runtime/common/config/basic.rs
  runtime/common/config/consensus.rs
  runtime/common/config/governance.rs
  runtime/common/constants.rs
  runtime/lagoon/src/weights/frame_election_provider_support.rs
  runtime/lagoon/src/weights/mod.rs
  runtime/tidechain/src/weights/frame_election_provider_support.rs
  runtime/tidechain/src/weights/mod.rs
  scripts/run_benches_for_runtime.sh
  utils/generate-bags/Cargo.toml
  utils/generate-bags/src/main.rs
Labels: A0-pleasereview, C1-low 📌, B1-releasenotes, D1-audited 👍

#105 fix `ExistentialDeposit`
  runtime/common/config/basic.rs
  runtime/common/config/governance.rs
  runtime/common/config/tidefi.rs
Labels: A0-pleasereview, C1-low 📌, B0-silent, D3-trivial 🧸

#104 Update benchmarks
  Cargo.lock
  frame/oracle/src/benchmarking.rs
  frame/quorum/src/benchmarking.rs
  runtime/common/api.rs
  runtime/lagoon/Cargo.toml
  runtime/lagoon/src/weights/frame_election_provider_support.rs
  runtime/lagoon/src/weights/frame_system.rs
  runtime/lagoon/src/weights/pallet_asset_registry.rs
  runtime/lagoon/src/weights/pallet_assets.rs
  runtime/lagoon/src/weights/pallet_balances.rs
  runtime/lagoon/src/weights/pallet_bounties.rs
  runtime/lagoon/src/weights/pallet_collective.rs
  runtime/lagoon/src/weights/pallet_election_provider_multi_phase.rs
  runtime/lagoon/src/weights/pallet_elections_phragmen.rs
  runtime/lagoon/src/weights/pallet_fees.rs
  runtime/lagoon/src/weights/pallet_identity.rs
  runtime/lagoon/src/weights/pallet_im_online.rs
  runtime/lagoon/src/weights/pallet_indices.rs
  runtime/lagoon/src/weights/pallet_membership.rs
  runtime/lagoon/src/weights/pallet_multisig.rs
  runtime/lagoon/src/weights/pallet_oracle.rs
  runtime/lagoon/src/weights/pallet_preimage.rs
  runtime/lagoon/src/weights/pallet_quorum.rs
  runtime/lagoon/src/weights/pallet_scheduler.rs
  runtime/lagoon/src/weights/pallet_session.rs
  runtime/lagoon/src/weights/pallet_staking.rs
  runtime/lagoon/src/weights/pallet_tidefi.rs
  runtime/lagoon/src/weights/pallet_tidefi_stake.rs
  runtime/lagoon/src/weights/pallet_timestamp.rs
  runtime/lagoon/src/weights/pallet_treasury.rs
  runtime/lagoon/src/weights/pallet_utility.rs
  runtime/tidechain/Cargo.toml
Labels: A0-pleasereview, C1-low 📌, B1-releasenotes, D2-notlive 💤

#111 Removed a duplicated check of request id existence in Swaps map.
  frame/oracle/src/lib.rs
Labels: A0-pleasereview, C3-medium 📣, B0-silent, D9-needsaudit 👮, E5-breaksapi

#110 Added a customised error InvalidMarketMakerRequestId with an index in the SwapConfirmation list
  frame/oracle/src/lib.rs
  frame/oracle/src/tests.rs
Labels: A0-pleasereview, C3-medium 📣, B1-releasenotes, D9-needsaudit 👮
