Repository tidelabs/tidechain, pull requests merged in 2022-07, with the labels that each got.

#178 Support `base_chain` in Onboarding Rebates
  frame/quorum/src/lib.rs
Labels: A0-pleasereview, C1-low 📌, B0-silent, D1-audited 👍

#180 Implement Sunrise pool leftover
  frame/fees/src/mock.rs
  frame/fees/src/tests.rs
  frame/oracle/src/mock.rs
  frame/quorum/src/mock.rs
  frame/sunrise/src/lib.rs
  frame/sunrise/src/mock.rs
  frame/sunrise/src/tests.rs
  frame/tidefi/src/mock.rs
  node/service/src/chain_spec.rs
  runtime/common/config/tidefi.rs
Labels: A0-pleasereview, C1-low 📌, B1-releasenotes, D1-audited 👍

#179 More assertions for `claim_sunrise_rewards`
  frame/tidefi/src/tests.rs
Labels: A0-pleasereview, C1-low 📌, B0-silent, D3-trivial 🧸

#181 Implement `FastTrackVotingPeriod`
  Cargo.lock
  node/service/src/chain_spec.rs
  runtime/common/api.rs
  runtime/common/config/governance.rs
  runtime/lagoon/Cargo.toml
  runtime/lagoon/src/lib.rs
  runtime/lagoon/src/weights/mod.rs
  runtime/lagoon/src/weights/pallet_democracy.rs
  runtime/tidechain/Cargo.toml
  runtime/tidechain/src/lib.rs
  runtime/tidechain/src/weights/mod.rs
  runtime/tidechain/src/weights/pallet_democracy.rs
Labels: A0-pleasereview, C9-critical ‼️, B1-releasenotes, D3-trivial 🧸, E1-runtimemigration, E2-databasemigration

#184 add `StakeStatus` to `AccountStakes`
  Cargo.lock
  frame/tidefi-stake/src/lib.rs
  frame/tidefi-stake/src/tests.rs
Labels: A0-pleasereview, C1-low 📌, B1-releasenotes, D1-audited 👍
