Repository tidelabs/tidechain, pull requests merged in 2022-05, with the labels that each got.

#113 Refactor oracle errors and tests
  frame/oracle/src/lib.rs
  frame/oracle/src/tests.rs
Labels: A0-pleasereview, C3-medium 📣, B1-releasenotes, D9-needsaudit 👮

#122 Refactor oracle errors and tests (phase 2)
  frame/oracle/src/lib.rs
  frame/oracle/src/tests.rs
Labels: A0-pleasereview, C1-low 📌, B1-releasenotes, D9-needsaudit 👮

#130 Update substrate
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  frame/asset-registry/Cargo.toml
  frame/fees/Cargo.toml
  frame/oracle/Cargo.toml
  frame/quorum/Cargo.toml
  frame/security/Cargo.toml
  frame/tidefi-rpc/Cargo.toml
  frame/tidefi-rpc/src/lib.rs
  frame/tidefi-stake/Cargo.toml
  frame/tidefi/Cargo.toml
  node/client/Cargo.toml
  node/client/src/lib.rs
  node/rpc/Cargo.toml
  node/rpc/src/lib.rs
  node/service/Cargo.toml
  node/service/src/lib.rs
  runtime/common/config/consensus.rs
  runtime/lagoon/Cargo.toml
  runtime/lagoon/src/lib.rs
  runtime/lagoon/src/weights/pallet_utility.rs
  runtime/tidechain/Cargo.toml
  runtime/tidechain/src/lib.rs
  runtime/tidechain/src/weights/pallet_utility.rs
Labels: A0-pleasereview, C1-low 📌, B1-releasenotes, D1-audited 👍

#124 Added a test
  frame/oracle/src/tests.rs
Labels: A0-pleasereview, C1-low 📌, B0-silent, D9-needsaudit 👮

#132 Quorum prevent multiple vote same member
  frame/quorum/src/lib.rs
Labels: A0-pleasereview, C3-medium 📣, B1-releasenotes, D9-needsaudit 👮

#135 Simplify Quorum helper functions
  frame/quorum/src/lib.rs
Labels: A0-pleasereview, C1-low 📌, B0-silent, D9-needsaudit 👮

#139 Expose `ArithmeticError` for ops
  frame/oracle/src/lib.rs
Labels: A0-pleasereview, C1-low 📌, B1-releasenotes, D1-audited 👍

#142 Prevent overflow on high decimals number
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  frame/asset-registry/Cargo.toml
  frame/fees/Cargo.toml
  frame/oracle/Cargo.toml
  frame/oracle/src/lib.rs
  frame/oracle/src/tests.rs
  frame/quorum/Cargo.toml
  frame/security/Cargo.toml
  frame/tidefi-rpc/Cargo.toml
  frame/tidefi-stake/Cargo.toml
  frame/tidefi/Cargo.toml
  node/client/Cargo.toml
  node/rpc/Cargo.toml
  node/service/Cargo.toml
  runtime/lagoon/Cargo.toml
  runtime/lagoon/src/lib.rs
  runtime/tidechain/Cargo.toml
  runtime/tidechain/src/lib.rs
Labels: A0-pleasereview, C9-critical ‼️, B1-releasenotes, D1-audited 👍
