Repository tidelabs/tidechain, pull requests merged in 2022-06, with the labels that each got.

#140 Refactor `pallet-tidefi` tests
  frame/assets/src/functions.rs
  frame/assets/src/lib.rs
  frame/tidefi/src/lib.rs
  frame/tidefi/src/mock.rs
  frame/tidefi/src/tests.rs
Labels: A0-pleasereview, C1-low 📌, B1-releasenotes, D9-needsaudit 👮

#141 Verbose errors for `pallet-assets`
  frame/assets/src/functions.rs
  frame/assets/src/lib.rs
Labels: A0-pleasereview, C1-low 📌, B0-silent, D9-needsaudit 👮

#146 Refactor `tidefi-stake` tests
  frame/tidefi-stake/src/lib.rs
  frame/tidefi-stake/src/mock.rs
  frame/tidefi-stake/src/tests.rs
Labels: A0-pleasereview, C1-low 📌, B0-silent, D9-needsaudit 👮

#147 Refactor `unstake` extrinsic
  frame/tidefi-stake/src/lib.rs
Labels: A0-pleasereview, C1-low 📌, B0-silent, D9-needsaudit 👮

#154 Add `OnChainSeqPhragmen` as election backup
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  cli/src/command.rs
  frame/asset-registry/Cargo.toml
  frame/assets/src/tests.rs
  frame/fees/Cargo.toml
  frame/fees/src/tests.rs
  frame/oracle/Cargo.toml
  frame/quorum/Cargo.toml
  frame/security/Cargo.toml
  frame/tidefi-rpc/Cargo.toml
  frame/tidefi-stake/Cargo.toml
  frame/tidefi/Cargo.toml
  node/client/Cargo.toml
  node/rpc/Cargo.toml
  node/service/Cargo.toml
  runtime/common/config/consensus.rs
  runtime/lagoon/Cargo.toml
  runtime/lagoon/src/lib.rs
  runtime/tidechain/Cargo.toml
  runtime/tidechain/src/lib.rs
Labels: A0-pleasereview, C1-low 📌, B0-silent, D1-audited 👍
