Repository tidelabs/tidechain, pull requests merged in 2022-10, with the labels that each got.

#226 Fix staking genesis
  frame/tidefi-stake/src/lib.rs
Labels: A0-pleasereview, C1-low 📌, B0-silent, D1-audited 👍

#230 Add funds releases tests
  frame/oracle/src/lib.rs
  frame/tidefi/src/mock.rs
  frame/tidefi/src/tests.rs
Labels: A0-pleasereview, C1-low 📌, B0-silent, D9-needsaudit 👮

#213 Assert trading rebates total
  node/service/src/chain_spec.rs
Labels: A0-pleasereview, C1-low 📌, B0-silent, D9-needsaudit 👮

#198 Better `unstaking` assertions
  frame/tidefi-stake/src/tests.rs
Labels: A0-pleasereview, C1-low 📌, B0-silent, D9-needsaudit 👮

#233 Restart Lagoon
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  frame/asset-registry/Cargo.toml
  frame/fees/Cargo.toml
  frame/oracle/Cargo.toml
  frame/quorum/Cargo.toml
  frame/security/Cargo.toml
  frame/sunrise/Cargo.toml
  frame/tidefi-rpc/Cargo.toml
  frame/tidefi-stake/Cargo.toml
  frame/tidefi-stake/src/lib.rs
  frame/tidefi/Cargo.toml
  frame/tidefi/src/benchmarking.rs
  node/client/Cargo.toml
  node/rpc/Cargo.toml
  node/service/Cargo.toml
  node/service/res/lagoon.json
  node/service/src/chain_spec.rs
  runtime/lagoon/Cargo.toml
  runtime/lagoon/src/lib.rs
  runtime/tidechain/Cargo.toml
  runtime/tidechain/src/lib.rs
Labels: A0-pleasereview, C1-low 📌, B1-releasenotes, D1-audited 👍, A1-needsburnin

#239 Prevent slippage overflow on swap
  frame/oracle/src/lib.rs
  frame/oracle/src/tests.rs
Labels: A0-pleasereview, C1-low 📌, B1-releasenotes, D1-audited 👍

#243 Allow transfer of all funds (skip keep-alive)
  frame/tidefi/src/lib.rs
  frame/tidefi/src/tests.rs
Labels: A0-pleasereview, C1-low 📌, B1-releasenotes, D1-audited 👍
