Repository tidelabs/tidechain, pull requests merged in 2023-06, with the labels that each got.

#328 Benchmarked oracle.confirm_swap extrinsic and also fixed some github workflow warnings
  .github/workflows/publish-draft-release.yml
  frame/oracle/src/benchmarking.rs
  runtime/lagoon/src/weights/pallet_oracle.rs
  runtime/tidechain/src/weights/pallet_oracle.rs
Labels: C1-low 📌, B0-silent, D3-trivial 🧸, A2-insubstantial

#237 Renamed tide to tdfy in code
  frame/sunrise/src/lib.rs
  node/service/src/chain_spec.rs
Labels: A0-pleasereview, C1-low 📌, B0-silent, D9-needsaudit 👮

#333 Updated Cargo.lock file
  Cargo.lock
Labels: A0-pleasereview, C1-low 📌, B0-silent, A1-needsburnin

#334 Bypass false positive redundant_closure_call clippy lints
  frame/assets/src/lib.rs
  frame/assets/src/types.rs
Labels: A0-pleasereview, C1-low 📌, B0-silent, A1-needsburnin

#335 Disable redundant closure call clippy lint.
  .cargo/config.toml
  frame/assets/src/lib.rs
  frame/assets/src/types.rs
Labels: A0-pleasereview, C1-low 📌, B0-silent, A1-needsburnin

#337 Update .gitlab-ci.yml
  .gitlab-ci.yml
Labels: A0-pleasereview

#340 Fixed timeout indentation in gitlab-ci
  .gitlab-ci.yml
Labels: A0-pleasereview, C1-low 📌, B0-silent, A1-needsburnin

#344 Updated variables used for dockerhub
  .github/workflows/publish-docker-release.yml
Labels: A0-pleasereview, C1-low 📌, B0-silent, A1-needsburnin

#346 Updated docker image name
  .gitlab-ci.yml
Labels: C1-low 📌, B0-silent, A2-insubstantial

#348 Updated docker image username to cicdtide
  .gitlab-ci.yml
Labels: C1-low 📌, B0-silent, A2-insubstantial

#350 Rollback docker image org name from cicdtide to tidelabs
  .gitlab-ci.yml
Labels: C1-low 📌, B0-silent, A2-insubstantial
